export const SET_USER = "SET_USER";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATAGORIES = "GET_CATAGORIES"; 
export const GET_SALES = "GET_SALES"; 
export const GET_DASHBOARD_SALES_DATA = "GET_DASHBOARD_SALES_DATA"; 
export const GET_DASHBOARD_INITIALS = "GET_DASHBOARD_INITIALS"; 
export const GET_PRODUCTS_ADDED_MONTHLY = "GET_PRODUCTS_ADDED_MONTHLY"; 


export const SERVER_API = "http://localhost:3001";